"""changed name to NOT unique

Revision ID: 0b5f27b63cba
Revises: f520dd246110
Create Date: 2023-09-18 20:29:14.541282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b5f27b63cba'
down_revision = 'f520dd246110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
